# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 273ffd17eaeff5ecc5ad40639c1b01899ed68b44c64c56e087045b8930fcb973301297c748b69894b93701c5de72e4fbe12e34f9ff836c09fa205b1754de7658

test:
  secret_key_base: 3e18f218e92eeba97b655a2cc47d59a0ad7094a12a171a0d02da95b56d661e8a110677b72a86e0548c15062fd5a6f78c4528ac62021ece529a8da780fbe41df5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
